# Generated by Django 4.1 on 2023-06-13 15:55

import django.core.validators
from django.db import migrations, models
import documents.validators


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='document_uploads', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'mp4', 'mov', 'avi', 'mp3', 'wav', 'aac', 'zip']), documents.validators.FileSizeValidator(max_size=10485760)]),
        ),
    ]
