SECRET_KEY = 'django-insecure-=hf+7_$!#%v#2x+(qdpnj#40luq58v_x9ea9iq9pn_ll92aj=i'

DEBUG = True
ALLOWED_HOSTS = []


ACCOUNT_ACTIVATION_DAYS = 7
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'email'

EMAIL_HOST_USER = '****@gmail.com'
EMAIL_HOST_PASSWORD = '*****'
